### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by thosil** [Streampunk/zenmos#1]
Hi I tried release and git version, but the behavior is the same, I got this error in the chrome javascript console:
```
Uncaught TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1232:7)
    at Object.eval (webpack-internal:///55:11:101)
    at eval (webpack-internal:///55:174:30)
    at Object.<anonymous> (http://localhost:9080/renderer.js:1075:1)
    at __webpack_require__ (http://localhost:9080/renderer.js:680:30)
    at fn (http://localhost:9080/renderer.js:90:20)
    at eval (webpack-internal:///122:2:144)
    at Object.<anonymous> (http://localhost:9080/renderer.js:1498:1)
    at __webpack_require__ (http://localhost:9080/renderer.js:680:30)
```
### My setup:
CentOS 7
Node.js v10.14.1
npm packages:
```
# npm ls --depth=0
zenmos@0.1.0 /home/tsi/projects/zenmos-0.1.0
├── ajv@6.4.0
├── babel-core@6.26.0
├── babel-eslint@7.2.3
├── babel-loader@7.1.4
├── babel-plugin-transform-runtime@6.23.0
├── babel-preset-env@1.6.1
├── babel-preset-stage-0@6.24.1
├── babel-register@6.26.0
├── babili-webpack-plugin@0.1.2
├── body-parser@1.18.2
├── cfonts@1.1.3
├── chalk@2.3.2
├── copy-webpack-plugin@4.5.1
├── cross-env@5.1.4
├── css-loader@0.28.11
├── del@3.0.0
├── devtron@1.4.0
├── digd.js@1.2.1 (git+https://git.coolaj86.com/scriptorian/digd.js#f180ff91d0bddec00777b5df103920b21a34fada)
├── dns-suite@1.2.11 (git+https://git.coolaj86.com/scriptorian/dns-suite.js#498d6f71f8fe49635f4ed1c89888c6f31bf36e80)
├── electron@1.8.4
├── electron-builder@20.8.1
├── electron-debug@1.5.0
├── electron-devtools-installer@2.2.3
├── eslint@4.19.1
├── eslint-config-google@0.9.1
├── eslint-friendly-formatter@3.0.0
├── eslint-loader@1.9.0
├── eslint-plugin-html@3.2.2
├── eslint-plugin-import@2.9.0
├── eslint-plugin-node@5.2.1
├── eslint-plugin-promise@3.7.0
├── eslint-plugin-standard@3.0.1
├── express@4.16.3
├── extract-text-webpack-plugin@3.0.2
├── file-loader@1.1.11
├── html-webpack-plugin@3.1.0
├── multispinner@0.2.1
├── node-loader@0.6.0
├── node-red@0.18.4
├── request@2.85.0
├── request-promise-native@1.0.5
├── sdpoker@0.0.8
├── style-loader@0.18.2
├── stylus@0.54.5
├── stylus-loader@3.0.2
├── tape@4.9.0
├── url-loader@1.0.1
├── uuid@3.2.1
├── vue@2.5.16
├── vue-electron@1.0.6
├── vue-html-loader@1.2.4
├── vue-loader@14.2.2
├── vue-router@3.0.1
├── vue-style-loader@4.1.0
├── vue-template-compiler@2.5.16
├── vuetify@1.0.10
├── webpack@3.11.0
├── webpack-dev-server@2.11.2
├── webpack-hot-middleware@2.21.2
└── yargs@11.0.0
```
### Steps to reproduce:
```
git clone..
cd zenmos
npm install
npm run dev
```

**Comment by sparkpunkd** [comment]
Unfortunately, Streampunk Media are not developing or supporting Zenmos at this time. The application is incomplete in its current form and was last checked in May 2018. The work-in-progress source code remains available if anyone wishes to develop the application further, e.g. through a pull request.
